version: '3.3'

services:
  redis:
    image: redis:alpine
    container_name: cache
    expose:
      - 6379

  web:
    links:
      - redis
      - mongo

    depends_on:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://cache
      - FORCE_COLOR=1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development

    command: npm run start:dev
    hostname: localhost
    container_name: node-container

    volumes:
      - ./src:/usr/src/app/src

    ports:
      - 3000:3000

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
      - 28017:28017
