module.exports = {
    CLIENT_ID: process.env.G_OAUTH_CLIENT_ID,
    CLIENT_SECRET: process.env.G_OAUTH_CLIENT_SECRET,
    OAUTH_REDIRECT_URL: process.env.G_OAUTH_REDIRECT_URL,
    ACCESS_TYPE: process.env.G_OAUTH_ACCESS_TYPE,
    PROMPT: process.env.G_OAUTH_PROMPT,
    AUTH_SUCCESS_REDIRECT_URL: process.env.AUTH_SUCCESS_REDIRECT_URL,
    AUTH_FAILURE_REDIRECT_URL: process.env.AUTH_FAILURE_REDIRECT_URL,
}